#ifndef INDEXEDWEDGES_HPP
#define INDEXEDWEDGES_HPP

#include <glad/glad.h>

#define RIGHT_EXTENT 0.8f
#define LEFT_EXTENT -RIGHT_EXTENT
#define TOP_EXTENT 0.20f
#define MIDDLE_EXTENT 0.0f
#define BOTTOM_EXTENT -TOP_EXTENT
#define FRONT_EXTENT -1.25f
#define REAR_EXTENT -1.75f

#define GREEN_COLOR 0.75f, 0.75f, 1.0f, 1.0f
#define BLUE_COLOR 	0.0f, 0.5f, 0.0f, 1.0f
#define RED_COLOR 1.0f, 0.0f, 0.0f, 1.0f
#define GREY_COLOR 0.8f, 0.8f, 0.8f, 1.0f
#define BROWN_COLOR 0.5f, 0.5f, 0.0f, 1.0f

namespace ogl
{
namespace
{

const float wedgesVertexData[] = {
  //Object 1 positions
  LEFT_EXTENT, TOP_EXTENT, REAR_EXTENT,
  LEFT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  RIGHT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  RIGHT_EXTENT, TOP_EXTENT,  REAR_EXTENT,

  LEFT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,
  LEFT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  RIGHT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  RIGHT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,

  LEFT_EXTENT, TOP_EXTENT,  REAR_EXTENT,
  LEFT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  LEFT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,

  RIGHT_EXTENT, TOP_EXTENT,  REAR_EXTENT,
  RIGHT_EXTENT, MIDDLE_EXTENT, FRONT_EXTENT,
  RIGHT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,

  LEFT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,
  LEFT_EXTENT, TOP_EXTENT,  REAR_EXTENT,
  RIGHT_EXTENT, TOP_EXTENT,  REAR_EXTENT,
  RIGHT_EXTENT, BOTTOM_EXTENT, REAR_EXTENT,

  //Object 2 positions
  TOP_EXTENT,  RIGHT_EXTENT, REAR_EXTENT,
  MIDDLE_EXTENT, RIGHT_EXTENT, FRONT_EXTENT,
  MIDDLE_EXTENT, LEFT_EXTENT, FRONT_EXTENT,
  TOP_EXTENT,  LEFT_EXTENT, REAR_EXTENT,

  BOTTOM_EXTENT, RIGHT_EXTENT, REAR_EXTENT,
  MIDDLE_EXTENT, RIGHT_EXTENT, FRONT_EXTENT,
  MIDDLE_EXTENT, LEFT_EXTENT, FRONT_EXTENT,
  BOTTOM_EXTENT, LEFT_EXTENT, REAR_EXTENT,

  TOP_EXTENT,  RIGHT_EXTENT, REAR_EXTENT,
  MIDDLE_EXTENT, RIGHT_EXTENT, FRONT_EXTENT,
  BOTTOM_EXTENT, RIGHT_EXTENT, REAR_EXTENT,

  TOP_EXTENT,  LEFT_EXTENT, REAR_EXTENT,
  MIDDLE_EXTENT, LEFT_EXTENT, FRONT_EXTENT,
  BOTTOM_EXTENT, LEFT_EXTENT, REAR_EXTENT,

  BOTTOM_EXTENT, RIGHT_EXTENT, REAR_EXTENT,
  TOP_EXTENT,  RIGHT_EXTENT, REAR_EXTENT,
  TOP_EXTENT,  LEFT_EXTENT, REAR_EXTENT,
  BOTTOM_EXTENT, LEFT_EXTENT, REAR_EXTENT,

  //Object 1 colors
  GREEN_COLOR,
  GREEN_COLOR,
  GREEN_COLOR,
  GREEN_COLOR,

  BLUE_COLOR,
  BLUE_COLOR,
  BLUE_COLOR,
  BLUE_COLOR,

  RED_COLOR,
  RED_COLOR,
  RED_COLOR,

  GREY_COLOR,
  GREY_COLOR,
  GREY_COLOR,

  BROWN_COLOR,
  BROWN_COLOR,
  BROWN_COLOR,
  BROWN_COLOR,

  //Object 2 colors
  RED_COLOR,
  RED_COLOR,
  RED_COLOR,
  RED_COLOR,

  BROWN_COLOR,
  BROWN_COLOR,
  BROWN_COLOR,
  BROWN_COLOR,

  BLUE_COLOR,
  BLUE_COLOR,
  BLUE_COLOR,

  GREEN_COLOR,
  GREEN_COLOR,
  GREEN_COLOR,

  GREY_COLOR,
  GREY_COLOR,
  GREY_COLOR,
  GREY_COLOR,
};

const int wedgesNumVertices = 36;

const GLushort wedgesIndexData[] =
{
  0, 2, 1,
  3, 2, 0,

  4, 5, 6,
  6, 7, 4,

  8, 9, 10,
  11, 13, 12,

  14, 16, 15,
  17, 16, 14,
};

const int wedgesNumElements = sizeof(wedgesIndexData) / sizeof(GLushort);

} // namespace
} // namespace ogl

#endif // INDEXEDWEDGES_HPP
